
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.psp.escuela;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.5
 * 2020-02-26T17:08:30.582+01:00
 * Generated source version: 3.3.5
 *
 */

@javax.jws.WebService(
                      serviceName = "escuela",
                      portName = "escuelaSOAP",
                      targetNamespace = "http://www.example.org/escuela/",
                      wsdlLocation = "file:/C:/Users/gemel/eclipse-workspace/ProyectoPSP/WebContent/WSDL-APP/WSDLFile.wsdl",
                      endpointInterface = "com.psp.escuela.Escuela")

public class EscuelaSOAPImpl implements Escuela {

    private static final Logger LOG = Logger.getLogger(EscuelaSOAPImpl.class.getName());

    /* (non-Javadoc)
     * @see com.psp.escuela.Escuela#escuelaevaluacion(com.psp.escuela.EvaluacionRequest parameters)*
     */
    public com.psp.escuela.EvaluacionResponse escuelaevaluacion(EvaluacionRequest parameters) {
        LOG.info("Executing operation escuelaevaluacion");
        System.out.println(parameters);
        try {
            com.psp.escuela.EvaluacionResponse _return = new com.psp.escuela.EvaluacionResponse();
            _return.setGreet("Greet948964042");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.psp.escuela.Escuela#escuelaalumno(com.psp.escuela.AlumnoRequest parameters)*
     */
    public com.psp.escuela.AlumnoResponse escuelaalumno(AlumnoRequest parameters) {
        LOG.info("Executing operation escuelaalumno");
        System.out.println(parameters);
        try {
            com.psp.escuela.AlumnoResponse _return = new com.psp.escuela.AlumnoResponse();
            _return.setGreet("Greet-42530942");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.psp.escuela.Escuela#escuelaasignatura(com.psp.escuela.AsignaturaRequest parameters)*
     */
    public com.psp.escuela.AsignaturaResponse escuelaasignatura(AsignaturaRequest parameters) {
        LOG.info("Executing operation escuelaasignatura");
        System.out.println(parameters);
        try {
            com.psp.escuela.AsignaturaResponse _return = new com.psp.escuela.AsignaturaResponse();
            _return.setGreet("Greet938654410");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
