package com.psp.escuela;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.5
 * 2020-02-26T17:08:30.631+01:00
 * Generated source version: 3.3.5
 *
 */
@WebService(targetNamespace = "http://www.example.org/escuela/", name = "escuela")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface Escuela {

    @WebMethod(action = "http://www.example.org/esceula/escuelaevaluacion")
    @WebResult(name = "evaluacionResponse", targetNamespace = "http://www.example.org/escuela/", partName = "parameters")
    public EvaluacionResponse escuelaevaluacion(

        @WebParam(partName = "parameters", name = "evaluacionRequest", targetNamespace = "http://www.example.org/escuela/")
        EvaluacionRequest parameters
    );

    @WebMethod(action = "http://www.example.org/esceula/escuelaalumno")
    @WebResult(name = "alumnoResponse", targetNamespace = "http://www.example.org/escuela/", partName = "parameters")
    public AlumnoResponse escuelaalumno(

        @WebParam(partName = "parameters", name = "alumnoRequest", targetNamespace = "http://www.example.org/escuela/")
        AlumnoRequest parameters
    );

    @WebMethod(action = "http://www.example.org/escuela/escuelaasignatura")
    @WebResult(name = "asignaturaResponse", targetNamespace = "http://www.example.org/escuela/", partName = "parameters")
    public AsignaturaResponse escuelaasignatura(

        @WebParam(partName = "parameters", name = "asignaturaRequest", targetNamespace = "http://www.example.org/escuela/")
        AsignaturaRequest parameters
    );
}
